export enum Genre {
  HORROR = "Horror",
  THRILLER = "Thriller",
  COMEDY = "Comedy",
  ROMANCE = "Romance",
  FANTASY = "Fantasy",
  ADVENTURE = "Adventure",
  ANTIWAR = "Anti-war",
  DRAMA = "Drama",
  ACTION = "Action",
  SCIFI = "Science-fiction",
  DYSTOPIAN = "Dystopian",
  POSTMODERN = "Postmodern",
  ANTHOLOGY = "Anthology",
  NONFICT = "Non-fiction",
}
